#!/usr/bin/env bash
#
# Generate the TechStack list with PLACEHOLDERS
#
# Author: Dave Eddy <dave@daveeddy.com>
# License: MIT

. ./theme || exit

UNDERLINE=$'\x1b[3m'

format-box() {
    local title=$1
    shift

    if [[ -z $1 ]]; then
        return
    fi
    local cmd_re='^(\$ [^ ]+)(.*)$'
    {
        echo '%'
        local line a b c icon name url
        
        for line in "$@"; do
            IFS='%' read -r a b c <<< "$line"

            # Logic to split Icon%Name%Description
            if [[ -n $c ]]; then
                icon=$a
                name=$b
                url=$c
            else
                icon=""
                name=$a
                url=$b
            fi

            # Print Placeholder (aligned with 2 spaces)
            if [[ -n $icon ]]; then
                 echo "  $icon"
            fi

            # Print Name
            if [[ $name =~ $cmd_re ]]; then
                local cmd=${BASH_REMATCH[1]}
                local rest=${BASH_REMATCH[2]}
                echo -n "$COLOR3$cmd$RST$COLOR5$rest"
            else
                echo -n "$COLOR3$name$RST"
            fi

            echo -n '%'
            echo -n "$COLOR1$UNDERLINE$url$RST"
            echo
        done
    } | ./tools/box -s '%' -hp 1 -tc "$COLOR5" -T plain -t "$title"
}

full='false'
while getopts 'f' opt; do
    case "$opt" in
        f) full='true';;
        *) exit 1;;
    esac
done

# === TECH STACK WITH PLACEHOLDERS ===
# We use these codes so the box draws correctly.
# We will swap them for images later in make-commands-jsonp
legend=(
    '__K__%Linux%Operating System / Kali'
    '__B__%BurpSuite%Web Vulnerability Scanner'
    '__W__%WireShark%Network Protocol Analyzer'
    '__N__%Nmap%Network Discovery & Auditing'
)

resources=()
extras=()

if $full; then
    legend+=(
        '__M__%Metasploit%Penetration Testing Framework'
        '__P__%Python%Scripting & Automation'
    )

    resources+=(
        'Bash%Shell Scripting'
    )

    extras+=(
        'Git%Version Control'
        'Docker%Containerization'
    )
fi

format-box TechStack "${legend[@]}"
format-box Resources "${resources[@]}"
format-box Extras "${extras[@]}"