#!/usr/bin/env bash
#
# Create the JSONP file for the web terminal
# INJECTS IMAGES WITH CLEANER STYLING
#
# Author: Dave Eddy <dave@daveeddy.com>
# License: MIT

# Style: 35px height, centered vertically, with 5px bottom margin
STYLE="height:35px; vertical-align:middle; margin-bottom:5px;"

# Define the Image Tags
IMG_KALI="<img src='static/img/kali.png' style='$STYLE' />"
IMG_BURP="<img src='static/img/burp.jpg' style='$STYLE' />"
IMG_WIRE="<img src='static/img/wireshark.png' style='$STYLE' />"
IMG_NMAP="<img src='static/img/nmap.jpg' style='$STYLE' />"
IMG_META="<img src='static/img/metasploit.png' style='$STYLE' />"
IMG_PYTH="<img src='https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg' style='$STYLE' />"

# Generate the raw terminal output
raw_output=$(./make-index | ./tools/bansi-to-html -H)

# SWAP PLACEHOLDERS
final_output=$(echo "$raw_output" | sed \
    -e "s|__K__|$IMG_KALI|g" \
    -e "s|__B__|$IMG_BURP|g" \
    -e "s|__W__|$IMG_WIRE|g" \
    -e "s|__N__|$IMG_NMAP|g" \
    -e "s|__M__|$IMG_META|g" \
    -e "s|__P__|$IMG_PYTH|g")

declare -A cmds
cmds['curl ysap.sh']="$final_output"

inputs=()
for cmd in "${!cmds[@]}"; do
    output=${cmds[$cmd]}
    s=$(jq -cnR --arg cmd "$cmd" --arg lines "$output" '{
        "cmd": $cmd,
        "lines": [$lines]
    }') || exit 1
    inputs+=("$s")
done

json=$(printf '%s\n' "${inputs[@]}" | jq -cn '[inputs]') || exit 1
echo "const COMMANDS = $json;"