#!/usr/bin/env bash
#
# Print the "about" message formatted how I like it - this output is intended to
# be piped into `tools/box`
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: April 05, 2025
# License: MIT

. ./theme || exit 1

readarray -t ABOUT << "EOF"
Hello Im Ralindu Geeman currently Undergraduagte in Bsc(Hons)Computer Networks.
Im a passionate cybercurity enthusiast with strong focus on problem-solving
and securing digital landscapes.

EOF

for line in "${ABOUT[@]}"; do
	echo "$COLOR1$line$RST"
done
