#!/usr/bin/env bash
#
# Create the JSONP file for the web terminal
# FIXED: Restores "Typing Animation" by splitting lines correctly
#
# Author: Dave Eddy <dave@daveeddy.com>
# License: MIT

# Style: 50px height, centered, with margin
STYLE="height:50px; vertical-align:middle; margin-right:10px;"

# Define the Image Tags
IMG_KALI="<img src='static/img/kali.png' style='$STYLE' />"
IMG_BURP="<img src='static/img/burp.jpg' style='$STYLE' />"
IMG_WIRE="<img src='static/img/wireshark.png' style='$STYLE' />"
IMG_NMAP="<img src='static/img/nmap.jpg' style='$STYLE' />"
IMG_META="<img src='static/img/metasploit.png' style='$STYLE' />"
IMG_PYTH="<img src='https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg' style='$STYLE' />"

# Generate the raw terminal output
raw_output=$(./make-index | ./tools/bansi-to-html -H)

# SWAP PLACEHOLDERS
# We inject the HTML image tags here
final_output=$(echo "$raw_output" | sed \
    -e "s|__K__|$IMG_KALI|g" \
    -e "s|__B__|$IMG_BURP|g" \
    -e "s|__W__|$IMG_WIRE|g" \
    -e "s|__N__|$IMG_NMAP|g" \
    -e "s|__M__|$IMG_META|g" \
    -e "s|__P__|$IMG_PYTH|g")

declare -A cmds
cmds['curl ysap.sh']="$final_output"

inputs=()
for cmd in "${!cmds[@]}"; do
    output=${cmds[$cmd]}
    
    # CRITICAL FIX HERE:
    # We use <<< "$output" at the end and [inputs] inside jq.
    # This reads the variable line-by-line and creates a JSON array.
    # The browser reads this array and "types" one line at a time.
    s=$(jq -cnR --arg cmd "$cmd" '{
        "cmd": $cmd,
        "lines": [inputs]
    }' <<< "$output") || exit 1
    
    inputs+=("$s")
done

json=$(printf '%s\n' "${inputs[@]}" | jq -cn '[inputs]') || exit 1
echo "const COMMANDS = $json;"